# Generated by Django 5.1.6 on 2025-02-27 03:18

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('date_de_naissance', models.DateField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('talents', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('singer', 'Chanteur/Chanteuse'), ('rapper', 'Rappeur/Rappeuse'), ('guitarist', 'Guitariste'), ('pianist', 'Pianiste'), ('drummer', 'Batteur/Batteuse'), ('violinist', 'Violoniste'), ('bassist', 'Bassiste'), ('composer', 'Compositeur/Compositrice'), ('dj', 'DJ'), ('lyricist', 'Parolier/Parolière')], max_length=78, null=True)),
                ('genres', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('pop', 'Pop'), ('rock', 'Rock'), ('hiphop', 'Hip-Hop'), ('rap', 'Rap'), ('jazz', 'Jazz'), ('classical', 'Classique'), ('electronic', 'Électronique'), ('rnb', 'R&B'), ('reggae', 'Reggae'), ('blues', 'Blues'), ('metal', 'Metal'), ('country', 'Country'), ('soul', 'Soul')], max_length=81, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('date_de_naissance', models.DateField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('studio_name', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('genres', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('pop', 'Pop'), ('rock', 'Rock'), ('hiphop', 'Hip-Hop'), ('rap', 'Rap'), ('jazz', 'Jazz'), ('classical', 'Classique'), ('electronic', 'Électronique'), ('rnb', 'R&B'), ('reggae', 'Reggae'), ('blues', 'Blues'), ('metal', 'Metal'), ('country', 'Country'), ('soul', 'Soul')], max_length=81, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
